platform :ios, '6.0.1'
pod 'CupertinoYankee', '~> 1.0.0'
pod 'AFNetworking', '~> 2.2.1'
pod 'TouchXML', '~> 0.1'
pod 'KGModal', '~> 1.1.0'
pod 'SSZipArchive', '~> 0.3.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'UICircularSlider', '~> 1.0.3'
pod 'FXBlurView', '~> 1.6.1'
pod 'SWRevealViewController', '~> 1.1.1'
